# Generated by Django 4.2 on 2023-05-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuSitesAll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.TextField()),
            ],
            options={
                'db_table': 'ru_sites_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitrixOnSites',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bitrix_analysis.rusitesall')),
                ('domain', models.TextField()),
                ('found_bitrix', models.BooleanField(default=False)),
                ('had_redirect', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'bitrix_on_sites',
                'managed': False,
            },
        ),
    ]
